spring.application.name=pg-vector-search
#spring.ai.openai.api-key=x
server.port: 9099
#spring.ai.openai.api-key=x
spring.ai.openai.api-key=x
#spring.main.allow-bean-definition-overriding=true

#spring.data.mongodb.uri=mongodb://192.168.10.216:27017/ankit

#spring.datasource.hikari.schema=ankit
spring.datasource.password=root
#spring.datasource.url=jdbc:postgresql://192.168.10.216:5432/ankit
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.default_schema=ankit
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
#spring.jpa.properties.hibernate.format_sql=ture
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=true
#spring.jpa.show-sql=false

#spring:
#  main:
#    allow-bean-definition-overriding: true
#  data:
#    mongodb:
#      uri: mongodb://192.168.10.216:27017/ankit
#  datasource:
#    hikari:
#      schema: ankit
#    password: root
#    url: jdbc:postgresql://192.168.10.216:5432/ankit
#    username: postgres
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        default_schema: ankit
#        enable_lazy_load_no_trans: true
#        format_sql: false
#        temp:
#          use_jdbc_metadata_defaults: false
#    show-sql: false